version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my_network

  amanah-be-app:
    build:
      context: .
    container_name: amanah-be-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: mongodb
    depends_on:
      - mongodb
    networks:
      - my_network
